name: Upstream Sync

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  sync_latest_from_upstream:
    name: Sync latest commits from upstream repo
    runs-on: ubuntu-latest
    if: ${{ github.event.repository.fork }}

    steps:
      - name: Sync upstream changes
        run: gh repo sync ${{ github.repository }} --source linguo2625469/workbuddy2api-panel --branch main
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
